name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4
    
      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Executa o build do projeto
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4
    
      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Executa os testes
        run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4
    
      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Gera o pacote
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso"

    
