name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4

  lint_and_test:
    uses: ./.github/workflows/lint-and-test.yml

  package:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4
    
      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Gera o pacote
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso"

    
