name: CI

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Executar testes?'
        required: false
        default: true
        type: boolean
      run_lint:
        description: 'Executar lint?'
        required: false
        default: true
        type: boolean
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'

jobs:
  lint_and_test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_tests: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true' }}
      run_lint: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_lint == 'true' }}

  package:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4
    
      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Gera o pacote
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso"

    
