name: Pipeline com Hello

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_job:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem
        !@#!@3asda: 
          echo "Pipeline iniciado com sucesso"
