name: Lint e Teste

on:
  workflow_call:
    inputs:
      run_lint:
        required: true
        type: boolean
      run_tests:
        required: true
        type: boolean

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    name: Verifica o estilo do código
    runs-on: ubuntu-latest
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4

      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instala dependências sem os testes
        run: mvn clean install -DskipTests

      - name: Executa a verificação de estilo
        run: mvn checkstyle:checkstyle

  test:
    if: ${{ inputs.run_tests }}
    name: Realiza os testes
    runs-on: ubuntu-latest
    steps:
      - name: Faz o checkout
        uses: actions/checkout@v4

      - name: Configura o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Realiza os testes
        run: mvn test
